<?php

/**
 * Application_Model_UzytkownicyHas_TestyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Application_Model_UzytkownicyHas_TestyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Application_Model_UzytkownicyHas_TestyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Application_Model_UzytkownicyHas_Testy');
    }
    
    public function getByIdUzytkownicyAndIdTesty($idUzytkownicy, $idTesty)
    {
        $query = Doctrine_Query::create()
                ->from('Application_Model_UzytkownicyHas_Testy')
                ->addWhere('Uzytkownicy_idUzytkownicy = ?', $idUzytkownicy)
                ->addWhere('Testy_idTesty = ?', $idTesty);
        
        return $query->execute();
    }
}