<div class="post1">
    <div class="title">
        <h2>Lista testów i Akcje</h2>

    </div>

    <p> <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator/paginator.phtml'); ?> </p>
    <table class="standard">
        <tr>
            <th>Nazwa testu</th>
            <th>data_od</th>
            <th>data_do</th>
            <th colspan="1">Akcje</th>
        </tr>

        <?php foreach ($this->paginator as $value) : ?>
            <tr class="<?php echo $this->cycle(array("light", "dark"))->next() ?>">

                <td><?= $value['Nazwa_testu']; ?></td>
                <td><?= $value['data_od']; ?></td>
                <td><?= $value['data_do']; ?></td>
                <td id="akcje"><a href="/tests/edit/?id=<?= $value['idTesty'] ?>">Edytuj</a></td>
                
            </tr>
        <?php endforeach; ?>
    </table>



</div>












