



<link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->baseUrl; ?>/css/default.css" /> 


<!-- start content -->
<div id="content">

    <div class="post">
        <div class="title">
            <h2>Zarejestrowano użytkownika</h2>

        </div>
        <br/>
        <br/>
        <br/>

        Rejestracja przebiegła pomyślnie


    </div>

</div>
<!-- end content -->