<link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->baseUrl; ?>/css/default.css" /> 


<!-- start content -->
<div id="content">

    <div class="post">
        <div class="title">
            <h2>Zalogowany użytkownik</h2>

        </div>
        <br/>
        <br/>
        <br/>
        <? foreach($this->errors as $key => $val) {
            echo 'Pole '. $key. ' - ';
            foreach($val as $k => $v) {
                echo $v;
            }
            echo '<br>';
        }?>
        <?= $this->form; ?>



    </div>

</div>
<!-- end content -->