



<link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->baseUrl; ?>/css/default.css" /> 


<!-- start content -->
<div id="content">

    <div class="post">
        <div class="title">
            <h2>Zalogowany użytkownik</h2>

        </div>
        <br/>
        <br/>
        <br/>

        <ul type="square">
            <li><?= $this->login; ?></li></ul>



    </div>

</div>
<!-- end content -->
