<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Application_Model_Testy', 'doctrine');

/**
 * Application_Model_Base_Testy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idTesty
 * @property string $Nazwa_testu
 * @property string $idPrzedmioty
 * @property string $data od
 * @property string $data do
 * @property Doctrine_Collection $Przedmioty
 * @property Doctrine_Collection $Testy_Sprawdzone
 * @property Doctrine_Collection $TestyHas_Zadania
 * @property Doctrine_Collection $UzytkownicyHas_Testy
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Application_Model_Base_Testy extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Testy');
        $this->hasColumn('idTesty', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Nazwa_testu', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('idPrzedmioty', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('data od', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('data do', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Application_Model_Przedmioty as Przedmioty', array(
             'local' => 'idTesty',
             'foreign' => 'Testy_idTesty'));

        $this->hasMany('Application_Model_Testy_Sprawdzone as Testy_Sprawdzone', array(
             'local' => 'idTesty',
             'foreign' => 'idTesty_Sprawdzone'));

        $this->hasMany('Application_Model_TestyHas_Zadania as TestyHas_Zadania', array(
             'local' => 'idTesty',
             'foreign' => 'Testy_idTesty'));

        $this->hasMany('Application_Model_UzytkownicyHas_Testy as UzytkownicyHas_Testy', array(
             'local' => 'idTesty',
             'foreign' => 'Testy_idTesty'));
    }
}