<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Application_Model_Uzytkownicy', 'doctrine');

/**
 * Application_Model_Base_Uzytkownicy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUzytkownicy
 * @property string $login
 * @property string $haslo
 * @property string $email
 * @property integer $rola
 * @property integer $Grupy_idGrupy
 * @property Application_Model_Grupy $Grupy
 * @property Doctrine_Collection $RozwiazanieZadania
 * @property Doctrine_Collection $Testy_Sprawdzone
 * @property Doctrine_Collection $UzytkownicyHas_Przedmioty
 * @property Doctrine_Collection $UzytkownicyHas_Testy
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Application_Model_Base_Uzytkownicy extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Uzytkownicy');
        $this->hasColumn('idUzytkownicy', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('login', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('haslo', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('rola', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Grupy_idGrupy', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Application_Model_Grupy as Grupy', array(
             'local' => 'Grupy_idGrupy',
             'foreign' => 'idGrupy'));

        $this->hasMany('Application_Model_RozwiazanieZadania as RozwiazanieZadania', array(
             'local' => 'idUzytkownicy',
             'foreign' => 'Uzytkownicy_idUzytkownicy'));

        $this->hasMany('Application_Model_Testy_Sprawdzone as Testy_Sprawdzone', array(
             'local' => 'idUzytkownicy',
             'foreign' => 'Uzytkownicy_idUzytkownicy'));

        $this->hasMany('Application_Model_UzytkownicyHas_Przedmioty as UzytkownicyHas_Przedmioty', array(
             'local' => 'idUzytkownicy',
             'foreign' => 'Uzytkownicy_idUzytkownicy'));

        $this->hasMany('Application_Model_UzytkownicyHas_Testy as UzytkownicyHas_Testy', array(
             'local' => 'idUzytkownicy',
             'foreign' => 'Uzytkownicy_idUzytkownicy'));
    }
}