<div class="post1">
    <div class="title">
        <h2>Lista Wykładowców i Akcje</h2>

    </div>

    <p> <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator/paginator.phtml'); ?> </p>
    <table class="standard">
        <tr>
            <th>Login</th>

            <th colspan="3">Akcje</th>
        </tr>

        <?php foreach ($this->paginator as $value) : ?>
            <tr class="<?php echo $this->cycle(array("light", "dark"))->next() ?>">

                <td><?= $value['login']; ?></td>
                <td id="akcje"><a href="/users/select/id/<?php echo $value['idUzytkownicy']; ?>">Wiecej o użytkowniku</a></td>
                <td id="akcje"><a href="/users/editlecturer/id/<?php echo $value['idUzytkownicy']; ?>">Edycja</a></td>
                <?php echo '<td id="akcje"><a href="/users/deletelecturer/id/' . $value['idUzytkownicy'] . '" onclick="if(!confirm(\'Na pewno chcesz usunąć użytkownika : ' . $value['login'] . ' ? \' )) return false;">Usuń</a></td>'; ?>
            </tr>
        <?php endforeach; ?>
    </table>



</div>







