<div class="post1">
    <div class="post">
        <div class="title">
            <h2>Szukanie Użytkowników</h2>

        </div>

       <?php echo $this->form; ?>
        
    </div>
            <?php if($this->ispost == 'post') { ?>
            <p> <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator/paginator.phtml');?> </p>
<table class="standard">
	  <tr>
	    <th>idUzytkownicy</th>
	    <th>Login</th>
	    
            <th>Email</th>
            <th>Rola</th>
            <th>Grupy_idGrupy</th>
	    <th colspan="4">Akcje</th>
	  </tr>
 <?php 
 foreach ($this->paginator as $value)  : if($value['rola'] != Application_Model_Uzytkownicy::ROLE_ADMIN) { ?>
	    <tr class="<?php echo $this->cycle(array("light", "dark"))->next() ?>">
	      <td><?= $value['idUzytkownicy']; ?></td>
              <td><?= $value['login']; ?></td>
	      
              <td><?= $value['email']; ?></td>
              <td><?= Application_Model_Uzytkownicy::$role[$value['rola']]; ?></td>
              <td><?= $value['Grupy_idGrupy']; ?></td>
	      <td><a href="/users/editstudent/id/<?php echo $value['idUzytkownicy']; ?>">Edycja</a></td>
    
	      <?php echo '<td><a href="/users/deletestudent/id/'. $value['idUzytkownicy'] .'" onclick="if(!confirm(\'Na pewno chcesz usunąć użytkownika : '.$value['login'].' ? \' )) return false;">Usuń</a></td>'; ?>
	    </tr>
	 <?php } endforeach; ?>
	</table>
<?php } ?>

    </div>
