<div class="post1">
    <div class="post">
        <div class="title">
            <h2>Szukanie Użytkowników</h2>

        </div>

       <?php echo $this->form;?>
        
    </div>
            <?php  $auth = Zend_Auth::getInstance()->getStorage()->read();
                 if ($auth['rola'] == Application_Model_Uzytkownicy::ROLE_LECTURER) {
     if($this->ispost == 'post') { ?>
    
     
            
            <?php foreach ($this->paginator as $value)  :  ?>
            <?php if(count($this->paginator)!=0 && $value['rola'] == Application_Model_Uzytkownicy::ROLE_STUDENT) {?>
            <p> <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator/paginator.phtml');?> </p>
<table class="standard">
	  <tr>

	    <th>Login</th>
	
	    <th colspan="3">Akcje</th>
	 
  <?php 
foreach ($this->paginator as $value)  : if($value['rola'] != Application_Model_Uzytkownicy::ROLE_ADMIN) { ?>    
	    <tr class="<?php echo $this->cycle(array("light", "dark"))->next() ?>">
	      
              <td><?= $value['login']; ?></td>
	      
              <td id="akcje"><a href="/users/select/id/<?php echo $value['idUzytkownicy']; ?>">Wiecej o użytkowniku</a></td>
	      <td id="akcje"><a href="/users/editstudent/id/<?php echo $value['idUzytkownicy']; ?>">Edycja</a></td>
    
	      <?php echo '<td id="akcje"> <a href="/users/deletestudent/id/'. $value['idUzytkownicy'] .'" onclick="if(!confirm(\'Na pewno chcesz usunąć użytkownika : '.$value['login'].' ? \' )) return false;">Usuń</a></td>'; ?>
	    </tr>
         
	 <?php } endforeach;  ?>

	</table>
             <?php } endforeach;  ?>
          
<?php } }?>
            
            
                        <?php  
                 if ($auth['rola'] == Application_Model_Uzytkownicy::ROLE_ADMIN) {
     if($this->ispost == 'post') { ?>
    
     
            
            <?php foreach ($this->paginator as $value)  :  ?>
            <?php if(count($this->paginator)!=0 && $value['rola'] != Application_Model_Uzytkownicy::ROLE_ADMIN) {?>
            <p> <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator/paginator.phtml');?> </p>
<table class="standard">
	  <tr>

	    <th>Login</th>
	
	    <th colspan="3">Akcje</th>
	 
  <?php 
foreach ($this->paginator as $value)  : if($value['rola'] != Application_Model_Uzytkownicy::ROLE_ADMIN) { ?>    
	    <tr class="<?php echo $this->cycle(array("light", "dark"))->next() ?>">
	      
              <td><?= $value['login']; ?></td>
	      
              <td id="akcje"><a href="/users/select/id/<?php echo $value['idUzytkownicy']; ?>">Wiecej o użytkowniku</a></td>
	      <td id="akcje"><a href="/users/editstudent/id/<?php echo $value['idUzytkownicy']; ?>">Edycja</a></td>
    
	      <?php echo '<td id="akcje"> <a href="/users/deletestudent/id/'. $value['idUzytkownicy'] .'" onclick="if(!confirm(\'Na pewno chcesz usunąć użytkownika : '.$value['login'].' ? \' )) return false;">Usuń</a></td>'; ?>
	    </tr>
         
	 <?php } endforeach;  ?>

	</table>
             <?php } endforeach;  ?>
          
<?php } }?>
         
         
            
            <?php echo $this->wiadomosc; ?>

    </div>
