<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Application_Model_UzytkownicyHas_Przedmioty', 'doctrine');

/**
 * Application_Model_Base_UzytkownicyHas_Przedmioty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUzytkownicy_has_Przedmioty
 * @property integer $Przedmioty_idPrzedmioty
 * @property integer $Uzytkownicy_idUzytkownicy
 * @property Application_Model_Przedmioty $Przedmioty
 * @property Application_Model_Uzytkownicy $Uzytkownicy
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Application_Model_Base_UzytkownicyHas_Przedmioty extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Uzytkownicy_has_Przedmioty');
        $this->hasColumn('idUzytkownicy_has_Przedmioty', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Przedmioty_idPrzedmioty', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Uzytkownicy_idUzytkownicy', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Application_Model_Przedmioty as Przedmioty', array(
             'local' => 'Przedmioty_idPrzedmioty',
             'foreign' => 'idPrzedmioty'));

        $this->hasOne('Application_Model_Uzytkownicy as Uzytkownicy', array(
             'local' => 'Uzytkownicy_idUzytkownicy',
             'foreign' => 'idUzytkownicy'));
    }
}