<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Application_Model_UzytkownicyHas_Testy', 'doctrine');

/**
 * Application_Model_Base_UzytkownicyHas_Testy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Uzytkownicy_idUzytkownicy
 * @property integer $Testy_idTesty
 * @property Application_Model_Testy $Testy
 * @property Application_Model_Uzytkownicy $Uzytkownicy
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Application_Model_Base_UzytkownicyHas_Testy extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Uzytkownicy_has_Testy');
        $this->hasColumn('Uzytkownicy_idUzytkownicy', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Testy_idTesty', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Application_Model_Testy as Testy', array(
             'local' => 'Testy_idTesty',
             'foreign' => 'idTesty'));

        $this->hasOne('Application_Model_Uzytkownicy as Uzytkownicy', array(
             'local' => 'Uzytkownicy_idUzytkownicy',
             'foreign' => 'idUzytkownicy'));
    }
}