
<link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->baseUrl; ?>/css/default.css" /> 


<!-- start content -->
<div id="content">

    <div class="post">
        <div class="title">
            <h2>Witamy na stronie głównej</h2>

        </div>


        <br/>
        <br/>
        <br/>
        <br/>
        <p>Noodle zawiera kursy e-learningowe stworzone przez nauczycieli.</p>

        <p>Aby móc w pełni korzystać z zasobów Noodle, musisz się zalogować.</p>
        <br/>
        <br/>
        <br/>
        <br/>


    </div>

</div>
<!-- end content -->
