
<link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->baseUrl; ?>/css/default.css" /> 


<!-- start content -->
<div id="content">

    <div class="post">
        <div class="title">
            <h2>Logowanie</h2>

        </div>
        <?=
        $this->loginForm;

        /*
         * To change this template, choose Tools | Templates
         * and open the template in the editor.
         */
        ?>
    </div>

</div>
<!-- end content -->
