<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : Mr. Techie
Version    : 1.0
Released   : 20070822
Description: Three-column blog design with the third column allocated for ads. Features Web 2.0 design ideal for 1024x768 resolutions.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Noodle</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/css/default.css" rel="stylesheet" type="text/css" media="screen" />
<script type="text/javascript" src="/jquery.min.js"></script>
<link href="/css/normalize.css" rel="stylesheet" type="text/css" media="screen" />
<link href="/css/datepicker.css" rel="stylesheet" type="text/css" media="screen" />
<link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js" rel="stylesheet" type="text/css" media="screen" />
<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
<script src="/jquery.ui.datepicker-pl.js"></script>

<script>

$(document).ready(function() {
var Event = function (text, className) {
    this.text = text;
    this.className = className;
};

var events = {};
    <?php   $daty = Application_Model_TestyTable::getInstance()->findAll()->toArray();
   
    $auth = Zend_Auth::getInstance()->getStorage()->read();
   
    
   if( $auth['rola'] != Application_Model_Uzytkownicy::ROLE_ADMIN && $auth['rola'] != NULL) {
foreach ($daty as $data) :

    echo 'events[new Date("'.$data['data_od'].'")] = new Event("Rozpoczęcie testu : '.$data['Nazwa_testu'] .'", "green");'; 
    echo 'events[new Date("'.$data['data_do'].'")] = new Event("Zakończenie testu : '.$data['Nazwa_testu'] .'", "red");'; ?>  
            
         
        <?php  endforeach; } ?>


console.dir(events);




$("#datepicker").datepicker({
    beforeShowDay: function (date) {
        var event = events[date];
        if (event) {
            return [true, event.className, event.text];
        } else {
            return [true, '', ''];
        }
    }
});
    
});
  $(document).ready(function() {
  function myDate(){
  var now = new Date();

  var outHour = now.getHours();
  
  if(outHour<10){document.getElementById('HourDiv').innerHTML="0"+outHour;}
  else{document.getElementById('HourDiv').innerHTML=outHour;}

  var outMin = now.getMinutes();
  if(outMin<10){document.getElementById('MinutDiv').innerHTML="0"+outMin;}
  else{document.getElementById('MinutDiv').innerHTML=outMin;}

  var outSec = now.getSeconds();
  if(outSec<10){document.getElementById('SecDiv').innerHTML="0"+outSec;}
  else{document.getElementById('SecDiv').innerHTML=outSec;}


} myDate(); setInterval(function(){ myDate();}, 1000); });

</script>

</head>
<body>
<!-- start header -->
<div id="header">
	<div id="logo">
		<h1><a href="/">Noodle</a></h1>
		
	</div>
	<div id="clockDiv"></div>
  
  <div id="Content2">
  <div id="HourDiv"></div><span id="c">:</span><div id="MinutDiv"></div><span id="c">:</span><div id="SecDiv"></div>
  </div>
	
</div>
<!-- end header -->
<!-- star menu -->
<div class="footer top">
</div>
<!-- end menu -->
<!-- start page -->
<div id="page">

    <div id="content">
        <?php echo $this->layout()->content; ?>
    </div>


<!-- start sidebar -->
<div id="sidebar">
    <ul>
        <li id="categories">
            <h2>Twoje konto</h2>
            <ul>
                <?php $hasIdentity = Zend_Auth::getInstance()->hasIdentity(); ?>
                <?php if ($hasIdentity) : ?>
                <li><a href="<?= $this->url(array('controller' => 'login', 'action' => 'logout')) ?>">Wyloguj się</a></li>
                <?php
                $auth = Zend_Auth::getInstance()->getStorage()->read();
                
                if ($auth['rola'] != Application_Model_Uzytkownicy::ROLE_STUDENT) {

                    if ($auth['rola'] == Application_Model_Uzytkownicy::ROLE_LECTURER) {

                        echo '<li><a href="' . $this->url(array('controller' => 'register', 'action' => 'index')) . '">Rejestracja użytkownika</a></li>';
                        echo '<li><a href="' . $this->url(array('controller' => 'subject', 'action' => 'index')) . '">Rejestracja przedmiotu</a></li>';
                        echo '<li><a href="' . $this->url(array('controller' => 'users', 'action' => 'student')) . '">Lista studentów</a></li>';
                        echo '<li><a href="' . $this->url(array('controller' => 'users', 'action' => 'search')) . '">Szukaj studentów</a></li>';
                    }

                    if ($auth['rola'] == Application_Model_Uzytkownicy::ROLE_ADMIN) {

                        echo '<li><a href="' . $this->url(array('controller' => 'register', 'action' => 'index')) . '">Rejestracja użytkownika</a></li>';
                         echo '<li><a href="' . $this->url(array('controller' => 'users', 'action' => 'student')) . '">Lista studentów</a></li>';
                          echo '<li><a href="' . $this->url(array('controller' => 'users', 'action' => 'lecturer')) . '">Lista wykładowców</a></li>';
                          echo '<li><a href="' . $this->url(array('controller' => 'users', 'action' => 'search')) . '">Szukaj użytkowników</a></li>';
                    }
                }
                ?>
                
                    <?php else:
                    
                    echo '<li><a href="' . $this->url(array('controller' => 'login', 'action' => 'login')) . '">Logowanie</a></li>';
                
                    ?>
                <?php endif; ?>
            </ul>
            </li>
        <?php $auth = Zend_Auth::getInstance()->getStorage()->read();
        if ($auth != null ) : ?>
        <li id="categories">
            <h2>Twoje testy</h2>
            <ul>
            <?php if ($this->isCanAddTest) : ?>
                <li><a href="/tests/add">Dodaj test</a></li>
                <li><a href="/tests/gen">Generuj test</a></li>
                <li><a href="/tests/list">Lista wszystkich test-ów</a></li>
                <hr />
            <?php endif; ?>
                <?php if (!empty($this->testForStudent)): ?>
                <?php foreach ($this->testForStudent as $test) : ?>
                    <li><a href="/tests/?id=<?= $test->idTesty ?>"><?= $test->Nazwa_testu ?></a></li>
                <?php endforeach; ?>
                <?php else: ?>
                    Brak testów
                <?php endif; ?>
            </ul>
            
        </li>
        <?php endif; ?>
        <?php $auth = Zend_Auth::getInstance()->getStorage()->read();
        if ($auth != null && $auth['rola'] != Application_Model_Uzytkownicy::ROLE_STUDENT) : ?>
        <li id="tasks">
            <h2>Zadania</h2>
            <ul>
                <li><a href="/task/">Lista</a></li>
                <li><a href="/task/add">Dodaj</a></li>
            </ul>
        </li>
        <?php endif; ?>
        <?php $auth = Zend_Auth::getInstance()->getStorage()->read();
        if ($auth != null && $auth['rola'] != Application_Model_Uzytkownicy::ROLE_STUDENT) : ?>
        <li id="tasks">
            <h2>Lista Sprawdzonych</h2>
            <ul>
                <li><a href="/tests/points">Lista</a></li>
            </ul>
        </li>
        <?php endif; ?>
	<?php $auth = Zend_Auth::getInstance()->getStorage()->read();
        if ($auth != null && $auth['rola'] != Application_Model_Uzytkownicy::ROLE_STUDENT) : ?>
        <li id="subject">
            <h2>Przedmioty</h2>
            <ul>
                <li><a href="/subject/">Lista Przedmiotow</a></li>
                <li><a href="/subject/add">Dodaj przedmiot</a></li>
            </ul>
        </li>
        <?php endif; ?>
        <li id="calendar">
            <h2>Kalendarz</h2>
            <div id="datepicker"></div>
        </li>

    </ul>
</div>
<!-- end sidebar -->
    
</div>
<!-- end page -->
<!-- start footer -->
<div class="footer">
</div>
<!-- end footer -->
</body>
</html>






