<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : Mr. Techie
Version    : 1.0
Released   : 20070822
Description: Three-column blog design with the third column allocated for ads. Features Web 2.0 design ideal for 1024x768 resolutions.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Noodle</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/css/default.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<!-- start header -->
<div id="header">
	<div id="logo">
		<h1><a href="/">Noodle</a></h1>
		
	</div>
	<div id="rss"></div>
	<div id="search">
		<form id="searchform" method="get" action="">
			<fieldset>
				<input type="text" name="s" id="s" size="15" value="" />
				<input type="submit" id="x" value="Search" />
			</fieldset>
		</form>
	</div>
</div>
<!-- end header -->
<!-- star menu -->
<div id="menu">
	<ul>
		<li class="current_page_item"><a href="/">Strona Główna</a></li>
	
	</ul>
</div>
<!-- end menu -->
<!-- start page -->
<div id="page">

	
			
                    <?php echo $this->layout()->content; ?>


<!-- start sidebar -->
<div id="sidebar">
    <ul>
        <li id="categories">
            <h2>Twoje konto</h2>
            <ul>
                <?php $hasIdentity = Zend_Auth::getInstance()->hasIdentity(); ?>
                <?php if ($hasIdentity) : ?>
                <li><a href="<?= $this->url(array('controller' => 'login', 'action' => 'logout')) ?>">Wyloguj się</a></li>
                <?php
                $auth = Zend_Auth::getInstance()->getStorage()->read();
                
                if ($auth['rola'] != Application_Model_Uzytkownicy::ROLE_STUDENT) {

                    if ($auth['rola'] == Application_Model_Uzytkownicy::ROLE_LECTURER) {

                        echo '<li><a href="' . $this->url(array('controller' => 'register', 'action' => 'index')) . '">Rejestracja</a></li>';
                    }

                    if ($auth['rola'] == Application_Model_Uzytkownicy::ROLE_ADMIN) {

                        echo '<li><a href="' . $this->url(array('controller' => 'register', 'action' => 'index')) . '">Rejestracja</a></li>';
                    }
                }
                ?>
                
                    <?php else:
                    
                    echo '<li><a href="' . $this->url(array('controller' => 'login', 'action' => 'login')) . '">Logowanie</a></li>';
                
                    ?>
                <?php endif; ?>
            </ul>
        </li>
        <li id="calendar">
            <h2>Kalendarz</h2>
            <div id="calendar_wrap">
                <table id="wp-calendar" summary="Calendar">
                    <caption>
                        August 2007
                    </caption>
                    <thead>
                        <tr>
                            <th abbr="Monday" scope="col" title="Monday">M</th>
                            <th abbr="Tuesday" scope="col" title="Tuesday">T</th>
                            <th abbr="Wednesday" scope="col" title="Wednesday">W</th>
                            <th abbr="Thursday" scope="col" title="Thursday">T</th>
                            <th abbr="Friday" scope="col" title="Friday">F</th>
                            <th abbr="Saturday" scope="col" title="Saturday">S</th>
                            <th abbr="Sunday" scope="col" title="Sunday">S</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td abbr="July" colspan="3" id="prev"><a href="#">&laquo; Jul</a></td>
                            <td class="pad">&nbsp;</td>
                            <td abbr="September" colspan="3" id="next" class="pad"><a href="#">Sep &raquo;</a></td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <td colspan="2" class="pad">&nbsp;</td>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                            <td>4</td>
                            <td>5</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>7</td>
                            <td>8</td>
                            <td>9</td>
                            <td>10</td>
                            <td>11</td>
                            <td>12</td>
                        </tr>
                        <tr>
                            <td>13</td>
                            <td>14</td>
                            <td>15</td>
                            <td>16</td>
                            <td>17</td>
                            <td>18</td>
                            <td>19</td>
                        </tr>
                        <tr>
                            <td>20</td>
                            <td id="today">21</td>
                            <td>22</td>
                            <td>23</td>
                            <td>24</td>
                            <td>25</td>
                            <td>26</td>
                        </tr>
                        <tr>
                            <td>27</td>
                            <td>28</td>
                            <td>29</td>
                            <td>30</td>
                            <td>31</td>
                            <td class="pad" colspan="2">&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </li>

    </ul>
</div>
<!-- end sidebar -->
    
</div>
<!-- end page -->
<!-- start footer -->
<div id="footer">
	<p class="legal">
		 </p>
	<p class="links">
		<a href="http://validator.w3.org/check/referer" class="xhtml" title="This page validates as XHTML">Valid <abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a>
		&nbsp;&bull;&nbsp;
		<a href="http://jigsaw.w3.org/css-validator/check/referer" class="css" title="This page validates as CSS">Valid <abbr title="Cascading Style Sheets">CSS</abbr></a>
	</p>
</div>
<!-- end footer -->
</body>
</html>






