<?php

/**
 * Application_Model_RozwiazanieZadaniaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Application_Model_RozwiazanieZadaniaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Application_Model_RozwiazanieZadaniaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Application_Model_RozwiazanieZadania');
    }
    
    public function findOneByIdzadaniaIdUser($idZadania, $idUser)
    {
        $query = Doctrine_Query::create()
                ->from('Application_Model_RozwiazanieZadania')
                ->andWhere('', $idZadania)
                ->andWhere('Uzytkownicy_idUzytkownicy = ?', $idUser);
        
        return $query->fetchOne();
        
    }
}