<?php

/**
 * Application_Model_ZadaniaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Application_Model_ZadaniaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Application_Model_ZadaniaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Application_Model_Zadania');
    }
    
    public function getZadanie($idZadania)
    {
        $query = Doctrine_Query::create()
                ->from('Application_Model_Zadania as Zadania')
                ->where('idZadania = ?', $idZadania);
        
        return $query->fetchOne();
    }
}