<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Application_Model_TestyHas_Zadania', 'doctrine');

/**
 * Application_Model_Base_TestyHas_Zadania
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Testy_idTesty
 * @property integer $Zadania_idZadania
 * @property Application_Model_Testy $Testy
 * @property Application_Model_Zadania $Zadania
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Application_Model_Base_TestyHas_Zadania extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Testy_has_Zadania');
        $this->hasColumn('Testy_idTesty', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Zadania_idZadania', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Application_Model_Testy as Testy', array(
             'local' => 'Testy_idTesty',
             'foreign' => 'idTesty'));

        $this->hasOne('Application_Model_Zadania as Zadania', array(
             'local' => 'Zadania_idZadania',
             'foreign' => 'idZadania'));
    }
}