<?php

/**
 * Application_Model_TestyHas_ZadaniaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Application_Model_TestyHas_ZadaniaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Application_Model_TestyHas_ZadaniaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Application_Model_TestyHas_Zadania');
    }
}