<table>
<?php foreach ($this->subject as $przedmioty) : ?>
        <tr>
            <td>
                <?= $przedmioty->nazwa ?>
            </td>
            <td>
                <?= $przedmioty->kierunek ?>
            </td>
            <td>
                <?= $przedmioty->grupa ?>
            </td>
            <td>
                <a href="/subject/edit/?id=<?= $przedmioty->idPzedmioty ?>">Edytuj</a>
            </td>
            <td>
                <a href="/?? jak wpisac kontroler remove? ??/?id=<?= $przedmioty->idPzedmioty ?>">Usun</a>
            </td>
        </tr>
<?php endforeach; ?>
</table>